{{- if (include "couchbase-cluster.tls.is-legacy" .) -}}
{{ $tls := fromYaml ( include "couchbase-cluster.tls.legacy" . ) }}
{{ if .Values.tls.generate }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "couchbase-cluster.tls.operator-secret" . }}
data:
  ca.crt: {{ $tls.caCert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "couchbase-cluster.tls.server-secret" . }}
data:
  chain.pem: {{ $tls.serverCert }}
  pkey.key: {{ $tls.serverKey }}
{{- end -}}
{{- end -}}
