{{ if not .Values.DEBUG }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.SERVICE_NAME }}
  name: {{ .Values.SERVICE_NAME }}
spec:
  replicas: {{ .Values.REPLICAS }}
  selector:
    matchLabels:
      app: {{ .Values.SERVICE_NAME }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.SERVICE_NAME }}
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
      - name: fluentbit
        image: grafana/fluent-bit-plugin-loki:main
        imagePullPolicy: IfNotPresent         
        ports:
          - name: metrics
            containerPort: 2020
            protocol: TCP
        volumeMounts:
          - name: config-volume
            mountPath: /fluent-bit/etc/
          - name: log-volume
            mountPath: var/log/shoppinglist
      - resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        image: "oltur/{{ .Values.SERVICE_NAME }}:{{ .Values.SERVICE_VERSION }}"
        name: {{ .Values.SERVICE_NAME }}
        imagePullPolicy: Always
        volumeMounts:
          - name: log-volume
            mountPath: var/log/shoppinglist
        ports:
          - containerPort: 80
        env:
        - name: "COUCHBASE_PASSWORD"
          valueFrom:
            secretKeyRef:
              key:  COUCHBASE_PASSWORD
              name: {{ .Release.Name }}-{{ .Values.SERVICE_NAME }}-db
        - name: "COUCHBASE_CONNECTION_STRING"
          value: {{ .Values.COUCHBASE_CONNECTION_STRING }}
        - name: "COUCHBASE_USERNAME"
          value: {{ .Values.COUCHBASE_USERNAME }}
        - name: "COUCHBASE_BUCKET"
          value: {{ .Values.COUCHBASE_BUCKET }}
        - name : "SERVICE_NAME"
          value: {{ .Values.SERVICE_NAME }}
        - name: "SERVICE_VERSION"
          value: {{ .Values.SERVICE_VERSION }}
        - name: "OTEL_COLLECTOR_HOST"
          value: {{ .Values.OTEL_COLLECTOR_HOST }}
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            name: fluent-bit-config           
{{end}}