---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  labels:
    # fargate: "yes"
    # app.kubernetes.io/part-of: sidecar
    app.kubernetes.io/version: latest
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |-
    [SERVICE]
        HTTP_Server    On
        HTTP_Listen    0.0.0.0
        HTTP_PORT      2020
        Flush          1
        Daemon         Off
        Log_Level      debug
        Parsers_File   parsers.conf
    [INPUT]
        Name              tail
        Tag               *
        Path              /var/log/shoppinglist/*.log
        Parser            docker
        DB                /var/log/shoppinglist/flb_kube.db
        Mem_Buf_Limit     5MB
        Buffer_Chunk_size 32k
        Buffer_Max_size   32k  
    [Output]
        Name        stdout
        Match       *
    [Output]
        Name grafana-loki
        Match *
        # host loki.default.svc.cluster.local
        # port 3100
        Url http://loki.default.svc.cluster.local:3100/loki/api/v1/push
        TenantID ""
        BatchWait 1s
        BatchSize 1048576
        Labels {app="shoppinglist",job="fluent-bit"}
        RemoveKeys kubernetes,stream
        AutoKubernetesLabels false
        # LabelMapPath /fluent-bit/etc/labelmap.json
        LineFormat json
        LogLevel warn
  parsers.conf: |-
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%SZ