apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.SERVICE_NAME }}
  name: {{ .Values.SERVICE_NAME }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: {{ .Values.SERVICE_NAME }}
