apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
spec:
  capacity:
   storage: 10Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /tmp/loki
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker1.cluster-prod.turevskiy.kharkiv.ua   