apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  strategy: {}
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - image: oltur/user-service:$SERVICE_VERSION
        name: user-service
        imagePullPolicy: Always
        ports:
          - containerPort: 80
