COUCHBASE_CONNECTION_STRING: couchbase://couchbase-0000.couchbase
COUCHBASE_USERNAME: Administrator
COUCHBASE_PASSWORD:
COUCHBASE_BUCKET: default
SERVICE_VERSION: latest
DEBUG: false
SERVICE_NAME: user-service
REPLICAS: 3
